from __future__ import annotations

from .checkpoint import CheckpointRecord, FilesystemCheckpointStore, ICheckpointStore, InMemoryCheckpointStore
from .config import BASE_MODEL_REGISTRY, BaseModelInfo, TrainingConfig
from .dataset import (
    ClipMetadata,
    ClipRecord,
    DatasetManager,
    DatasetStatistics,
    DatasetValidator,
    DatasetVersion,
    EmbeddingDuplicateDetector,
    FfprobeNotAvailableError,
    FilesystemDatasetVersionStore,
    HashDuplicateDetector,
    HeuristicCaptionProvider,
    ICaptionProvider,
    IDatasetValidator,
    IDatasetVersionStore,
    IDuplicateDetector,
    VLMCaptionProvider,
    assign_split,
    build_dataset_version,
    compute_statistics,
    compute_version_id,
    extract_clip_metadata,
    split_dataset,
)
from .errors import ModelUnavailableError
from .evaluation import (
    BenchmarkCase,
    BenchmarkCaseResult,
    BenchmarkResult,
    BenchmarkRunner,
    CLIPScoreMetric,
    DurationConformanceMetric,
    FVDMetric,
    HumanEvalRecord,
    IBenchmarkRunner,
    IEvaluationMetric,
    IHumanEvalStore,
    InMemoryHumanEvalStore,
    MetricResult,
    OutputExistsMetric,
    QualityReport,
    RegressionDetector,
    RegressionFinding,
    ResolutionConformanceMetric,
    build_quality_report,
    mean_rating,
)
from .lora import LoRAConfig, LoRAMergePlan
from .registry import (
    FilesystemModelRegistry,
    IModelRegistry,
    InvalidPromotionTransitionError,
    ModelRegistryError,
    ModelVersionRecord,
    PromotionStatus,
    UnknownModelVersionError,
    assert_valid_transition,
    validate_capability_manifest,
)
from .trainer import DryRunTrainer, ITrainer, TrainingRunResult
from .validation import ValidationIssue, ValidationResult

__all__ = [
    "BASE_MODEL_REGISTRY",
    "BaseModelInfo",
    "BenchmarkCase",
    "BenchmarkCaseResult",
    "BenchmarkResult",
    "BenchmarkRunner",
    "CLIPScoreMetric",
    "CheckpointRecord",
    "ClipMetadata",
    "ClipRecord",
    "DatasetManager",
    "DatasetStatistics",
    "DatasetValidator",
    "DatasetVersion",
    "DryRunTrainer",
    "DurationConformanceMetric",
    "EmbeddingDuplicateDetector",
    "FVDMetric",
    "FfprobeNotAvailableError",
    "FilesystemCheckpointStore",
    "FilesystemDatasetVersionStore",
    "FilesystemModelRegistry",
    "HashDuplicateDetector",
    "HeuristicCaptionProvider",
    "HumanEvalRecord",
    "IBenchmarkRunner",
    "ICaptionProvider",
    "ICheckpointStore",
    "IDatasetValidator",
    "IDatasetVersionStore",
    "IDuplicateDetector",
    "IEvaluationMetric",
    "IHumanEvalStore",
    "IModelRegistry",
    "ITrainer",
    "InMemoryCheckpointStore",
    "InMemoryHumanEvalStore",
    "InvalidPromotionTransitionError",
    "LoRAConfig",
    "LoRAMergePlan",
    "MetricResult",
    "ModelRegistryError",
    "ModelUnavailableError",
    "ModelVersionRecord",
    "OutputExistsMetric",
    "PromotionStatus",
    "QualityReport",
    "RegressionDetector",
    "RegressionFinding",
    "ResolutionConformanceMetric",
    "TrainingConfig",
    "TrainingRunResult",
    "UnknownModelVersionError",
    "VLMCaptionProvider",
    "ValidationIssue",
    "ValidationResult",
    "assert_valid_transition",
    "assign_split",
    "build_dataset_version",
    "build_quality_report",
    "compute_statistics",
    "compute_version_id",
    "extract_clip_metadata",
    "mean_rating",
    "split_dataset",
    "validate_capability_manifest",
]
