from __future__ import annotations

from contextlib import contextmanager
from time import perf_counter
from typing import Iterator

from prometheus_client import CONTENT_TYPE_LATEST, CollectorRegistry, Counter, Histogram, generate_latest

REGISTRY = CollectorRegistry()

HTTP_REQUESTS_TOTAL = Counter(
    "sallehly_http_requests_total",
    "Total HTTP requests handled by apps/api",
    ["method", "path", "status"],
    registry=REGISTRY,
)

HTTP_REQUEST_DURATION_SECONDS = Histogram(
    "sallehly_http_request_duration_seconds",
    "HTTP request duration in seconds",
    ["method", "path"],
    registry=REGISTRY,
)

GENERATION_JOBS_TOTAL = Counter(
    "sallehly_generation_jobs_total",
    "Total GenerationJobs completed, labeled by terminal status",
    ["status"],
    registry=REGISTRY,
)

GENERATION_JOB_DURATION_SECONDS = Histogram(
    "sallehly_generation_job_duration_seconds",
    "Wall-clock duration of a single GenerationPipeline.generate_plan() call",
    registry=REGISTRY,
)

RATE_LIMIT_REJECTIONS_TOTAL = Counter(
    "sallehly_rate_limit_rejections_total",
    "Total requests rejected with 429 by the rate limiter",
    ["scope"],
    registry=REGISTRY,
)


def render_metrics() -> tuple[bytes, str]:
    """Returns (body, content_type) for a `/metrics` route - real
    Prometheus exposition-format text, generated by `prometheus_client`
    itself from `REGISTRY`'s actual current counter/histogram state, not
    a canned string."""
    return generate_latest(REGISTRY), CONTENT_TYPE_LATEST


@contextmanager
def time_histogram(histogram: Histogram, **label_values: str) -> Iterator[None]:
    start = perf_counter()
    try:
        yield
    finally:
        elapsed = perf_counter() - start
        if label_values:
            histogram.labels(**label_values).observe(elapsed)
        else:
            histogram.observe(elapsed)
